=== Oppac/XML_projects/project_1/Bookshop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:bk="http://www.project1.be"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.project1.be"
  elementFormDefault="qualified">

  <xs:element name="Bookshop">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="bk:ScientificDepartement" />
        <xs:element ref="bk:LeisureDepartement" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="ScientificDepartement">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SBook" type="bk:ScientificBook" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="SJournal" type="bk:Journal" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="LeisureDepartement">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="LBook" type="bk:LeisureBook" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="LPeriodical" type="bk:Periodical" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="AllBooks">
    <xs:sequence>
      <xs:element name="Title" type="xs:string" />
      <xs:element name="Publisher" type="xs:string" />
      <xs:element name="PublicationYear" type="xs:gYear" />
      <xs:element name="Edition" type="xs:string" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ScientificBook">
    <xs:complexContent>
      <xs:extension base="bk:AllBooks">
        <xs:sequence>
          <xs:choice>
            <xs:element name="Authors" type="xs:string" maxOccurs="unbounded" />
            <xs:element name="Editors" type="xs:string" maxOccurs="unbounded" />
          </xs:choice>
          <xs:element name="Abstract" minOccurs="0">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:maxLength value="2500" />
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="ISBN">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{13}" />
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="LeisureBook">
    <xs:complexContent>
      <xs:extension base="bk:AllBooks">
        <xs:sequence>
          <xs:element name="Authors" type="xs:string" maxOccurs="unbounded" />
          <xs:element name="Genre">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="Thriller" />
                <xs:enumeration value="Horror" />
                <xs:enumeration value="Sci/fi" />
                <xs:enumeration value="Romance" />
                <xs:enumeration value="Literature" />
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="PageNumber" type="xs:positiveInteger" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="AllJournals">
    <xs:sequence>
      <xs:element name="Title" type="xs:string" />
      <xs:element name="Publisher" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Journal">
    <xs:complexContent>
      <xs:extension base="bk:AllJournals">
        <xs:sequence>
          <xs:element name="Volume" type="xs:positiveInteger" />
          <xs:element name="Number" type="xs:positiveInteger" />
          <xs:choice>
            <xs:element name="Authors" type="xs:string" maxOccurs="unbounded" />
            <xs:element name="Editors" type="xs:string" maxOccurs="unbounded" />
          </xs:choice>
          <xs:element name="PublicationYear" type="xs:gYear" />
          <xs:element name="ImpactFactor" type="bk:ImpactFactor" minOccurs="0" />
          <xs:element name="ContentTable" type="bk:ContentTable" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ImpactFactor">
    <xs:sequence>
      <xs:element name="ImpactFactorName" type="xs:string" />
      <xs:element name="ValidYear" type="xs:gYear" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ContentTable">
    <xs:sequence>
      <xs:element name="Article" type="bk:Article" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Article">
    <xs:sequence>
      <xs:element name="ArticleTitle" type="xs:string" />
      <xs:element name="ArticleAuthor" type="xs:string" maxOccurs="unbounded" />
      <xs:choice>
        <xs:sequence>
          <xs:element name="ArticleStart" type="xs:positiveInteger" />
          <xs:element name="ArticleEnd" type="xs:positiveInteger" />
        </xs:sequence>
        <xs:element name="ArticleNb" type="xs:positiveInteger" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Periodical">
    <xs:complexContent>
      <xs:extension base="bk:AllJournals">
        <xs:sequence>
          <xs:element name="Price" type="bk:PositiveDecimal" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="PositiveDecimal">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== Oppac/XML_projects/Bookshop.xml
<?xml version="1.0" encoding="UTF-8"?>
<Bks:Bookshop xmlns:Bks="http://www.bookshop.be"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.bookshop.be Bookshop.xsd">

<Bks:ScientificDepartement>
   <Bks:Book>
      <Bks:Title>The Origin of Species</Bks:Title>
      <Bks:Publisher>Castle Books</Bks:Publisher>
      <Bks:PublicationYear>1859</Bks:PublicationYear>
      <Bks:Edition>English edition</Bks:Edition>
      <Bks:Authors>Charles Darwin</Bks:Authors>
      <Bks:Abstract>Darwin's theory of natural selection
       issued a profound challenge to orthodox thought
       and belief: no being or species has been specifically
       created; all are locked into a pitiless struggle for existence,
      with extinction looming for those not fitted for the task.</Bks:Abstract>
      <Bks:ISBN>9780785819110</Bks:ISBN>
    </Bks:Book>
    <Bks:Book>
      <Bks:Title>Cosmos</Bks:Title>
      <Bks:Publisher>Mass Market</Bks:Publisher>
      <Bks:PublicationYear>2002</Bks:PublicationYear>
      <Bks:Edition>English edition</Bks:Edition>
      <Bks:Authors>Carl Sagan</Bks:Authors>
      <Bks:Abstract>In the book, Sagan explores 15 billion years of cosmic
       evolution and the development of science and civilization.
       Cosmos traces the origins of knowledge and the scientific method,
       mixing science and philosophy, and speculates to the future of science.
       The book also discusses the underlying premises of science by providing
       biographical anecdotes about many prominent scientists throughout history,
       placing their contributions into the broader context of the development
       of modern science.</Bks:Abstract>
      <Bks:ISBN>9780375508325</Bks:ISBN>
    </Bks:Book>
    <Bks:Book>
      <Bks:Title>Gödel, Escher, Bach: An Eternal Golden Braid</Bks:Title>
      <Bks:Publisher>Basic Books</Bks:Publisher>
      <Bks:PublicationYear>1999</Bks:PublicationYear>
      <Bks:Edition>Anniversary edition</Bks:Edition>
      <Bks:Authors>Douglas Hofstadter</Bks:Authors>
      <Bks:Abstract>Douglas Hofstadter's book is concerned directly with the nature
       of “maps” or links between formal systems. However, according to
       Hofstadter, the formal system that underlies all mental activity
       transcends the system that supports it. If life can grow out of the
       formal chemical substrate of the cell, if consciousness can emerge out
       of a formal system of firing neurons, then so too will computers
       attain human intelligence. Gödel, Escher, Bach is a wonderful
       exploration of fascinating ideas at the heart of cognitive science:
       meaning, reduction, recursion, and much more.</Bks:Abstract>
      <Bks:ISBN>9780465026562</Bks:ISBN>
    </Bks:Book>

=== Oppac/XML_projects/project_1/Bookshop2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Bookshop
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.project1.be Bookshop.xsd"
  xmlns="http://www.project1.be">

  <ScientificDepartement>
     <SBook>
        <Title>Anfrageoptimierung in objektrelationalen Datenbanken durch kostenbedingte Termersetzungen</Title>
        <Publisher>Aka Akademische Verlagsgesellschaft Aka GmbH</Publisher>
        <PublicationYear>2007</PublicationYear>
        <Edition>English</Edition>
        <Authors>Mazeyar E. Makoui</Authors>
        <Abstract>By now, I hope you’re convinced that you can use XSLT
				 to convert big piles of XML data into other useful things.
				 Our examples to this point have pretty much gone through the
				 XML source in what’s referred to as document order.
				 We’d like to go through our XML documents in a couple of other common ways.</Abstract>
        <ISBN>9783826616648</ISBN>
      </SBook>
      <SBook>
        <Title>Datenbanken: Konzepte und Sprachen</Title>
        <Publisher>Redline GmbH</Publisher>
        <PublicationYear>2008</PublicationYear>
        <Edition>Flamand</Edition>
        <Authors>Andreas Heuer</Authors>
        <Abstract>Es ist schwer unter der Hülle und Fülle der vorhandenen DB-Bücher
				  ein ansprechendes und gut geschriebenes und nach Möglichkeit
				  Stoffumfassendes Buch zu finden. Doch genau dies ist den Autoren Heuer und Saake gelungen.
				  Mit klaren Strukturen und Beispielen führen sie den Leser in die Welt der Datenbanken ein.
				  Jedes Kapitel wird zudem mit passenden Übungsaufgaben beendet,zu welchen es in Zukunft auf
				  der zum Buch begleitenden Homepage der Autoren auch Lösungen geben soll.</Abstract>
        <ISBN>7838266166410</ISBN>
      </SBook>
      <SBook>
        <Title>Understanding Planning Tasks: Domain Complexity and Heuristic Decomposition.</Title>
        <Publisher>Springer</Publisher>
        <PublicationYear>1999</PublicationYear>
        <Edition>Anniversary edition</Edition>
        <Authors>Malte Helmert</Authors>
        <Abstract>Action planning has always played a central role in Artificial Intelligence.
				  Given a description of the current situation, a description of possible actions
				  and a description of the goals to be achieved, the task is to identify a sequence of actions,
				  i.e., a plan that transforms the current situation into one that satisfies the goal description.
				  This monograph is a revised version of Malte Helmert's doctoral thesis, Solving Planning Tasks
				  in Theory and Practice, written under the supervision of Professor Bernhard Nebel as thesis advisor
				  at Albert-Ludwigs-Universität Freiburg, Germany, in 2006. The book contains an exhaustive analysis
				  of the computational complexity of the benchmark problems that have been used in the past decade,
				  namely the standard benchmark domains of the International Planning Competitions (IPC).
				  At the same time, it contributes to the practice of solving planning tasks by presenting a powerful
				  new approach to heuristic planning. The author also provides an in-depth analysis of so-called routing
				  and transportation problems..</Abstract>
        <ISBN>9783540777229</ISBN>
      </SBook>

      <SJournal>
        <Title>Inferring Regulations in a Genomic Network from Gene Expression Profiles.</Title>
        <Publisher>Springer Nature</Publisher>
        <Volume>1</Volume>
        <Number>320</Number>
        <Authors>Nasimul Noman</Authors>
        <Authors>Hitoshi Iba</Authors>
        <Authors>Davide Bau</Authors>
        <PublicationYear>2007</PublicationYear>
        <ImpactFactor>
          <ImpactFactorName>The Impact</ImpactFactorName>
          <ValidYear>2020</ValidYear>
        </ImpactFactor>
        <ContentTable>
          <Article>
            <ArticleTitle>Filtering Protein Surface Motifs Using Negative Instances of Active Sites Candidates</ArticleTitle>
            <ArticleAuthor>Takenao Ohkawa</ArticleAuthor>
            <ArticleNb>1</ArticleNb>
          </Article>
          <Article>
            <ArticleTitle>Distill: A Machine Learning Approach to Ab Initio Protein Structure Prediction</ArticleTitle>
            <ArticleAuthor>Alessandro Vullo</ArticleAuthor>
            <ArticleNb>2</ArticleNb>
          </Article>
          <Article>
            <ArticleTitle>Bioinformatics: Mining the Massive Data from High Throughput Genomics Experiments.</ArticleTitle>
            <ArticleAuthor>Sun Kim</ArticleAuthor>
            <ArticleNb>3</ArticleNb>
          </Article>
        </ContentTable>
      </SJournal>
      <SJournal>
        <Title>Combining Local and Global History Hashing in Perceptron Branch Prediction.</Title>
        <Publisher>Anthony Shi-Sheung Fong</Publisher>
        <Volume>1</Volume>
        <Number>544</Number>
        <Authors>C. Y. Ho</Authors>
        <Authors>Anthony Shi-Sheung Fong</Authors>
        <Authors>Zhongwen Li</Authors>
        <PublicationYear>2017</PublicationYear>
        <ContentTable>
          <Article>
            <ArticleTitle>Improving Interactive Experience of Thin Client Computing by Reducing Data Spikes</ArticleTitle>
            <ArticleAuthor>Sun Yang</ArticleAuthor>
            <ArticleAuthor>Tay Teng Tiow</ArticleAuthor>
            <ArticleNb>1</ArticleNb>
          </Article>
          <Article>
            <ArticleTitle>Massive Data Delivery in Unstructured Peer-to-Peer Networks with Network Coding</ArticleTitle>
            <ArticleAuthor>Zhongwen Li</ArticleAuthor>
            <ArticleNb>5</ArticleNb>
          </Article>
        </ContentTable>
      </SJournal>
  </ScientificDepartement>

  <LeisureDepartement>
    <LBook>
      <Title>The famour people</Title>
      <Publisher>Athula Ginige</Publisher>
      <PublicationYear>2008</PublicationYear>
      <Edition>English</Edition>
      <Authors>Jeewani Anupama Ginige</Authors>
      <Genre>Thriller</Genre>
      <PageNumber>460</PageNumber>
    </LBook>
    <LBook>
      <Title>Romantic Stories</Title>
      <Publisher>Mehdi Parviz</Publisher>
      <PublicationYear>1926</PublicationYear>
      <Edition>English</Edition>
      <Authors>Yousof Erfani</Authors>
      <Genre>Horror</Genre>
      <PageNumber>520</PageNumber>
    </LBook>
    <LBook>
      <Title>Appointement with girl friend </Title>
      <Publisher>Babak Pazand</Publisher>
      <PublicationYear>1970</PublicationYear>
      <Edition>English</Edition>
      <Authors>Chris McDonald</Authors>
      <Genre>Sci/fi</Genre>
      <PageNumber>240</PageNumber>
    </LBook>
    <LBook>
      <Title>Proud to be humain</Title>
      <Publisher>Ruhul A. Sarker</Publisher>
      <PublicationYear>1963</PublicationYear>
      <Edition>English</Edition>
      <Authors>David Cornforth</Authors>
      <Genre>Sci/fi</Genre>
      <PageNumber>244</PageNumber>
    </LBook>
    <LBook>
      <Title>Nobel price</Title>
      <Publisher>Modern house</Publisher>
      <PublicationYear>1813</PublicationYear>
      <Edition>English</Edition>
      <Authors>Peter E. Tischer</Authors>
      <Genre>Romance</Genre>
      <PageNumber>270</PageNumber>
    </LBook>
    <LBook>
      <Title>Monte Carlos history</Title>
      <Publisher>Mitp-Verlag</Publisher>
      <PublicationYear>1844</PublicationYear>
      <Edition>French</Edition>
      <Authors>Monte Carlos</Authors>
      <Genre>Literature</Genre>
      <PageNumber>1250</PageNumber>
    </LBook>

    <LPeriodical>
      <Title>Geographie</Title>
      <Publisher>The Geographie house</Publisher>
      <Price>7.50</Price>
    </LPeriodical>
    <LPeriodical>
      <Title>Sciences</Title>
      <Publisher>Kendrich house</Publisher>
      <Price>9.40</Price>
    </LPeriodical>
  </LeisureDepartement>
</Bookshop>
